title: "Ingrid Arreola"
email: inarreol@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  66 Days Of Data -- updated daily for the challenge!
baseurl: "/" 
url: "https://ingridarreola.github.io/" 
twitter_username: ingrid_arreola
github_username:  ingridarreola

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
